judge 2 fix
openproblems-bio/task-dge-perturbation-prediction pull request #24
Opened 2024-05-10 15:21 UTC by wangmengbo

1. extract pre-defined cell type used for coarse training as an argument.
1. complete viash pipeline testing in docker mode on my local machine.

2024-05-11 07:44 UTC, rcannood requested changes
Thanks @wangmengbo ! I made a few suggestions. With these changes, hopefully the CI will pass!

2024-05-11 07:44 UTC, rcannood commented on scripts/add_a_method.sh
> +method_id="scape"
Please undo these changes -- they should not be modified for everybody else to see :relaxed: 

```suggestion
method_id="my_method"
```

2024-05-11 07:44 UTC, rcannood commented on scripts/add_a_method.sh
> +
```suggestion
```

2024-05-11 07:44 UTC, rcannood commented on src/task/methods/scape/config.vsh.yaml
> +      default: NK cells
The unit test runs out of memory on the CI. Could you add one or more arguments to the component with a `default` and a `test_default`? The default will be what gets used during the actual benchmark, while `test_default` is used during CI testing. For example:

```suggestion
      default: NK cells
    - type: integer
      name: --epochs
      description: ...Add description here...
      default: 300
      info:
        test_default: 2
    - type: integer
      name: --epochs_enhanced
      description: ...Add description here...
      default: 300
      info:
        test_default: 2

2024-05-11 07:44 UTC, rcannood commented on src/task/methods/scape/script.py
> +epochs_enhanced = 800
```suggestion
# fetch parameters
epochs = par["epochs"]
epochs_enhanced = par["epochs_enhanced"]

2024-05-13 03:24 UTC, wangmengbo commented
Hi, Robrecht. It seems the viash complains `test_default` being not correctly set. I'm not sure what's the exact reason causing viash cannot parse it. Any suggestion?

2024-05-13 14:55 UTC, rcannood commented
> Hi, Robrecht. It seems the viash complains `test_default` being not correctly set. I'm not sure what's the exact reason causing viash cannot parse it. Any suggestion?

It's not Viash complaining, it was a mistake in the unit test I added for the method components. Should be fixed now!

2024-05-13 23:23 UTC, wangmengbo commented
Thanks for fixing this. However, the test seems still be killed. I'll try do some gc during training.

2024-05-15 13:08 UTC, rcannood approved these changes

2024-05-15 13:08 UTC, merged